### ISSUE TITLE
Mod causes server lag spikes

### ISSUE THREAD

**Issue by alfuken** [coehlrich/chunk-logger#1]
```[12:19:40] [LagSpikeProfiler/INFO] [TickProfiler]: 
The server appears to have lag spiked.
Last tick 0.20571129s ago."Server thread" RUNNABLE
        at java.util.TimeZone.toZoneId(TimeZone.java:556)
        at java.time.ZoneId.systemDefault(ZoneId.java:274)
        at java.time.Clock.systemDefaultZone(Clock.java:178)
        at java.time.LocalDateTime.now(LocalDateTime.java:180)
        at com.coehlrich.chunklogger.chunk.AllChunks.onTick(AllChunks.java:69)
        at com.coehlrich.chunklogger.event.EventHandlerCommon.onServerTick(EventHandlerCommon.java:57)
        at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_1645_EventHandlerCommon_onServerTick_ServerTickEvent.invoke(.dynamic)
        at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
        at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
        at net.minecraftforge.fml.common.FMLCommonHandler.onPostServerTick(FMLCommonHandler.java:266)
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:712)
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
        at java.lang.Thread.run(Thread.java:745)
```

Probably, this mod needs to be rewritten a bit.

**Comment by coehlrich** [comment]
Sorry for the late response. I am actually in the middle of a massive rewrite of the mod.
